services:
  nextcloud:
    build: 
      context: .
      dockerfile: Dockerfile 
    container_name: nextcloud_custom
    restart: always
    volumes:
      - nextcloud_app:/var/www/html/nextcloud
      - nextcloud_data:/var/www/html/nextcloud/data
      - php_socket:/run/php
    networks:
      - nextcloud_net
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro        # Main NGINX config
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Site config
      - ./etc/letsencrypt/:/etc/letsencrypt/:ro  # Mount SSL certificates
      - nextcloud_app:/var/www/html/nextcloud
      - nextcloud_data:/var/www/html/nextcloud/data
      - php_socket:/run/php
    depends_on:
      - nextcloud
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTPS_PORT}:443"
    networks:
      - nextcloud_net

  db:
    image: mariadb:10.11
    container_name: nextcloud_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - mariadb_socket:/var/run/mysqld  # Use the same volume for MariaDB socket
    networks:
      - nextcloud_net

  backup:
    build:
      context: .
      dockerfile: Dockerfile-backup
    container_name: nextcloud_backup
    restart: always
    volumes:
      - nextcloud_app:/var/www/html/nextcloud
      - nextcloud_data:/var/www/html/nextcloud/data
      - db_data:/var/lib/mysql  # Read-only access to DB data
      - mariadb_socket:/var/run/mysqld  # Use the same volume for MariaDB socket
      - ./backup:/backup  # Store backups in a persistent directory
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - nextcloud_net

volumes:
  nextcloud_app:
  nextcloud_data:
  db_data:
  php_socket:
  mariadb_socket:  # Docker volume for MariaDB socket

networks:
  nextcloud_net:
